name: PRADO Forum
on: [push, pull_request]
jobs:
  checks:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, dom, intl, json, mbstring, pdo_sqlite, pdo_mysql, pdo_pgsql, openssl, pcre, spl, zlib
          tools: php-cs-fixer, phpstan, cs2pr

      - name: Validate composer.json
        run: composer validate --strict --no-check-lock

      - name: Validate code style using php-cs-fixer
        run: php-cs-fixer fix -vvv --dry-run --using-cache=no --format=checkstyle | cs2pr

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Validate code using phpstan
        run: phpstan analyse --memory-limit=512M --error-format=checkstyle | cs2pr

      - name: Run unit tests (SQLite)
        run: composer unittest

      - name: Setup mysql service
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -proot < ./tests/initdb_mysql.sql

      - name: Run unit tests (MySQL)
        run: composer unittest
        env:
          BEFORUM_TEST_DSN: mysql:host=127.0.0.1;dbname=beforum_unitest;charset=utf8mb4
          BEFORUM_TEST_USER: beforum_unitest
          BEFORUM_TEST_PASSWORD: beforum_unitest

      - name: Setup postgres service
        run: |
          createdb -h 127.0.0.1 -U postgres beforum_unitest
          psql -h 127.0.0.1 -U postgres -a -w beforum_unitest -f ./tests/initdb_pgsql.sql
        env:
          PGPASSWORD: postgres

      - name: Run unit tests (PostgreSQL)
        run: composer unittest
        env:
          BEFORUM_TEST_DSN: pgsql:host=127.0.0.1;dbname=beforum_unitest
          BEFORUM_TEST_USER: beforum_unitest
          BEFORUM_TEST_PASSWORD: beforum_unitest
